"""add_routine_tables

Revision ID: 0dfe34c1c026
Revises: 9984d31f026b
Create Date: 2026-03-20 11:22:49.042471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dfe34c1c026'
down_revision: Union[str, None] = '9984d31f026b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

sessiontype_enum = postgresql.ENUM('PLAN', 'RECITATION', name='sessiontype', create_type=False)

def upgrade() -> None:
    op.execute("DO $$ BEGIN CREATE TYPE sessiontype AS ENUM ('PLAN', 'RECITATION'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_routines_user', 'routines', ['user_id'], unique=False)
    op.create_table('routine_time_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('time_int', sa.Integer(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_time_blocks_routine', 'routine_time_blocks', ['routine_id'], unique=False)
    op.create_index('uq_routine_time', 'routine_time_blocks', ['routine_id', 'time'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('routine_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_block_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sessiontype_enum, nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['time_block_id'], ['routine_time_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_time_block', 'routine_sessions', ['time_block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessions_time_block', table_name='routine_sessions')
    op.drop_table('routine_sessions')
    op.drop_index('uq_routine_time', table_name='routine_time_blocks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_time_blocks_routine', table_name='routine_time_blocks')
    op.drop_table('routine_time_blocks')
    op.drop_index('idx_routines_user', table_name='routines')
    op.drop_table('routines')
    op.execute("DROP TYPE sessiontype")
    # ### end Alembic commands ###