"""drop created_by from series

Revision ID: 3a8f2b9c1d4e
Revises: f64f4649bf6f
Create Date: 2026-05-14 09:48:23.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8f2b9c1d4e'
down_revision: Union[str, None] = 'f64f4649bf6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('created_by', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###
