"""add recitation_collection tables

Revision ID: 402085623057
Revises: 4dc71853233a
Create Date: 2025-11-12 10:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402085623057'
down_revision: Union[str, None] = '4dc71853233a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recitation_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('img_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recitation_collections_user_id', 'recitation_collections', ['user_id'], unique=False)
    op.create_table('recitation_collection_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recitation_collection_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recitation_collection_id'], ['recitation_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recitation_collection_id', 'text_id', name='uq_recitation_collection_items_collection_text')
    )
    op.create_index('idx_recitation_collection_items_collection_id', 'recitation_collection_items', ['recitation_collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recitation_collection_items_collection_id', table_name='recitation_collection_items')
    op.drop_table('recitation_collection_items')
    op.drop_index('idx_recitation_collections_user_id', table_name='recitation_collections')
    op.drop_table('recitation_collections')
    # ### end Alembic commands ###
