"""drop duplicate text_images index

Revision ID: 64d3723c7834
Revises: 689da466a9f8
Create Date: 2026-02-03 12:32:59.910482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d3723c7834'
down_revision: Union[str, None] = '689da466a9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_text_images_text_id', table_name='text_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_text_images_text_id', 'text_images', ['text_id'], unique=False)
    # ### end Alembic commands ###
