"""add text_images table

Revision ID: 689da466a9f8
Revises: a54b63eb5fc3
Create Date: 2026-02-03 12:30:46.834650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689da466a9f8'
down_revision: Union[str, None] = 'a54b63eb5fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_text_images_text_id', 'text_images', ['text_id'], unique=False)
    op.create_index(op.f('ix_text_images_text_id'), 'text_images', ['text_id'], unique=False)
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_text_images_text_id'), table_name='text_images')
    op.drop_index('idx_text_images_text_id', table_name='text_images')
    op.drop_table('text_images')
    # ### end Alembic commands ###
