"""add segment_id to sub_tasks

Revision ID: 9984d31f026b
Revises: 40802d0e62bf
Create Date: 2026-02-12 13:49:17.668488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9984d31f026b'
down_revision: Union[str, None] = '40802d0e62bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_tasks', sa.Column('segment_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_tasks', 'segment_id')
    # ### end Alembic commands ###
