"""add_source_text_id_and_pecha_segment_id_to_subtasks

Revision ID: ba7fbc446df1
Revises: a54b63eb5fc3
Create Date: 2026-02-01 11:21:01.045459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7fbc446df1'
down_revision: Union[str, None] = 'a54b63eb5fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    op.add_column('sub_tasks', sa.Column('source_text_id', sa.UUID(), nullable=True))
    op.add_column('sub_tasks', sa.Column('pecha_segment_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_tasks', 'pecha_segment_id')
    op.drop_column('sub_tasks', 'source_text_id')
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
