"""add audio for plan

Revision ID: e26ae474faf3
Revises: c1d2e3f4a5b6
Create Date: 2026-05-25 13:42:50.963846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26ae474faf3'
down_revision: Union[str, None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_item_audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_item_id', sa.UUID(), nullable=False),
    sa.Column('audio_key', sa.String(length=1000), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_item_id')
    )
    op.create_index('idx_plan_item_audio_plan_item_id', 'plan_item_audio', ['plan_item_id'], unique=False)
    op.create_table('sub_task_timestamps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_task_id', sa.UUID(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sub_task_id'], ['sub_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_task_id')
    )
    op.create_index('idx_sub_task_timestamps_sub_task_id', 'sub_task_timestamps', ['sub_task_id'], unique=False)
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english', title || ' ' || COALESCE(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_search', table_name='plans', postgresql_using='gin')
    op.create_index('idx_plans_search', 'plans', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index('idx_sub_task_timestamps_sub_task_id', table_name='sub_task_timestamps')
    op.drop_table('sub_task_timestamps')
    op.drop_index('idx_plan_item_audio_plan_item_id', table_name='plan_item_audio')
    op.drop_table('plan_item_audio')
    # ### end Alembic commands ###
